name: Build Docker image

on:
  push:
    branches:
      - build_image
    tags:
      - 'v*.*.*'

env:
  GH_REGISTRY: ghcr.io
  GH_NAMESPACE: oceanum-io
  GAR_REGISTRY: us-central1-docker.pkg.dev
  GAR_PROJECT: oceanum-registry
  GAR_REPOSITORY: public
  IMAGE_NAME: oceanum-python
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]
        debian-version: [bookworm, trixie]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Split Versions
        id: split_versions
        run: |
          MAJOR_VERSION=$(echo ${{ github.ref_name }} | cut -d. -f1)
          MINOR_VERSION=$(echo ${{ github.ref_name }} | cut -d. -f2)
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_ENV

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_REGISTRY }}
          username: ${{ vars.GCP_AR_DOCKER_USERNAME }}
          password: ${{ secrets.GCP_AR_DOCKER_PASSWORD }}
          
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          #platforms: linux/amd64
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ env.GAR_REGISTRY }}/${{ env.GAR_PROJECT }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}-cache
          cache-to: type=registry,ref=${{ env.GAR_REGISTRY }}/${{ env.GAR_PROJECT }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}-cache
          build-args: |
            PYTHON_VER=${{ matrix.python-version }}
            DEBIAN_VER=${{ matrix.debian-version }}
          push: true
          tags: |
            ${{ env.GH_REGISTRY }}/${{ env.GH_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.GH_REGISTRY }}/${{ env.GH_NAMESPACE }}/${{ env.IMAGE_NAME }}:py${{ matrix.python-version }}-${{ matrix.debian-version }}
            ${{ env.GH_REGISTRY }}/${{ env.GH_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.MINOR_VERSION }}-py${{ matrix.python-version }}-${{ matrix.debian-version }}
            ${{ env.GH_REGISTRY }}/${{ env.GH_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.MINOR_VERSION }}.${{ env.MAJOR_VERSION }}-py${{ matrix.python-version }}-${{ matrix.debian-version }}
            ${{ env.GH_REGISTRY }}/${{ env.GH_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-py${{ matrix.python-version }}-${{ matrix.debian-version }}
            ${{ env.GAR_REGISTRY }}/${{ env.GAR_PROJECT }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.GAR_REGISTRY }}/${{ env.GAR_PROJECT }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:py${{ matrix.python-version }}-${{ matrix.debian-version }}
            ${{ env.GAR_REGISTRY }}/${{ env.GAR_PROJECT }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.MINOR_VERSION }}-py${{ matrix.python-version }}-${{ matrix.debian-version }}
            ${{ env.GAR_REGISTRY }}/${{ env.GAR_PROJECT }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.MINOR_VERSION }}.${{ env.MAJOR_VERSION }}-py${{ matrix.python-version }}-${{ matrix.debian-version }}